version: '3.8'

services:
  fastapi:
    build: ./project/app
    command: uvicorn project.app.WarehouseManagementApp:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev #  dev, test, prod
      - TESTING=0 #  0 - false, 1 - true